name: Build & Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Install readline
      run: sudo apt install libreadline-dev -y

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}
      run: ./build/tests/tests --gtest_print_time

    - name: Run Lisp Scripts
      run: |
        for file in ${{ github.workspace }}/tests/programs/*.lsp; do
          echo "Executing $file"
          time ${{ github.workspace }}/build/src/lisp $file
        done

    - name: Bundle Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: |
        mkdir -p ${{ github.workspace }}/release
        cp -v ${{ github.workspace }}/build/src/lisp ${{ github.workspace }}/release/
        cp -v -r ${{ github.workspace }}/stdlib ${{ github.workspace }}/release/
        tar -czvf lisp-linux-amd64.tar.gz -C ${{ github.workspace }}/release lisp stdlib
        pwd
        ls -la

    - name: Publish Relase
      uses: appleboy/scp-action@master
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      with:
        username: ${{ secrets.USER }}
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.KEY }}
        source: "lisp-linux-amd64.tar.gz"
        target: "/var/www/files/lisp/release/latest"
